# Autogenerated wrapper script for PHYLIP_jll for i686-linux-musl
export clique, consense, contml, contrast, dnacomp, dnadist, dnainvar, dnaml, dnamlk, dnamove, dnapars, dnapenny, dollop, dolmove, dolpenny, drawgram, drawtree, factor, fitch, gendist, kitsch, libdrawgram, libdrawtree, mix, move, neighbor, pars, penny, proml, promlk, protdist, protpars, restdist, restml, retree, seqboot, treedist

JLLWrappers.@generate_wrapper_header("PHYLIP")
JLLWrappers.@declare_library_product(libdrawgram, "libdrawgram.so")
JLLWrappers.@declare_library_product(libdrawtree, "libdrawtree.so")
JLLWrappers.@declare_executable_product(clique)
JLLWrappers.@declare_executable_product(consense)
JLLWrappers.@declare_executable_product(contml)
JLLWrappers.@declare_executable_product(contrast)
JLLWrappers.@declare_executable_product(dnacomp)
JLLWrappers.@declare_executable_product(dnadist)
JLLWrappers.@declare_executable_product(dnainvar)
JLLWrappers.@declare_executable_product(dnaml)
JLLWrappers.@declare_executable_product(dnamlk)
JLLWrappers.@declare_executable_product(dnamove)
JLLWrappers.@declare_executable_product(dnapars)
JLLWrappers.@declare_executable_product(dnapenny)
JLLWrappers.@declare_executable_product(dollop)
JLLWrappers.@declare_executable_product(dolmove)
JLLWrappers.@declare_executable_product(dolpenny)
JLLWrappers.@declare_executable_product(drawgram)
JLLWrappers.@declare_executable_product(drawtree)
JLLWrappers.@declare_executable_product(factor)
JLLWrappers.@declare_executable_product(fitch)
JLLWrappers.@declare_executable_product(gendist)
JLLWrappers.@declare_executable_product(kitsch)
JLLWrappers.@declare_executable_product(mix)
JLLWrappers.@declare_executable_product(move)
JLLWrappers.@declare_executable_product(neighbor)
JLLWrappers.@declare_executable_product(pars)
JLLWrappers.@declare_executable_product(penny)
JLLWrappers.@declare_executable_product(proml)
JLLWrappers.@declare_executable_product(promlk)
JLLWrappers.@declare_executable_product(protdist)
JLLWrappers.@declare_executable_product(protpars)
JLLWrappers.@declare_executable_product(restdist)
JLLWrappers.@declare_executable_product(restml)
JLLWrappers.@declare_executable_product(retree)
JLLWrappers.@declare_executable_product(seqboot)
JLLWrappers.@declare_executable_product(treedist)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libdrawgram,
        "lib/libdrawgram.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libdrawtree,
        "lib/libdrawtree.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        clique,
        "bin/clique",
    )

    JLLWrappers.@init_executable_product(
        consense,
        "bin/consense",
    )

    JLLWrappers.@init_executable_product(
        contml,
        "bin/contml",
    )

    JLLWrappers.@init_executable_product(
        contrast,
        "bin/contrast",
    )

    JLLWrappers.@init_executable_product(
        dnacomp,
        "bin/dnacomp",
    )

    JLLWrappers.@init_executable_product(
        dnadist,
        "bin/dnadist",
    )

    JLLWrappers.@init_executable_product(
        dnainvar,
        "bin/dnainvar",
    )

    JLLWrappers.@init_executable_product(
        dnaml,
        "bin/dnaml",
    )

    JLLWrappers.@init_executable_product(
        dnamlk,
        "bin/dnamlk",
    )

    JLLWrappers.@init_executable_product(
        dnamove,
        "bin/dnamove",
    )

    JLLWrappers.@init_executable_product(
        dnapars,
        "bin/dnapars",
    )

    JLLWrappers.@init_executable_product(
        dnapenny,
        "bin/dnapenny",
    )

    JLLWrappers.@init_executable_product(
        dollop,
        "bin/dollop",
    )

    JLLWrappers.@init_executable_product(
        dolmove,
        "bin/dolmove",
    )

    JLLWrappers.@init_executable_product(
        dolpenny,
        "bin/dolpenny",
    )

    JLLWrappers.@init_executable_product(
        drawgram,
        "bin/drawgram",
    )

    JLLWrappers.@init_executable_product(
        drawtree,
        "bin/drawtree",
    )

    JLLWrappers.@init_executable_product(
        factor,
        "bin/factor",
    )

    JLLWrappers.@init_executable_product(
        fitch,
        "bin/fitch",
    )

    JLLWrappers.@init_executable_product(
        gendist,
        "bin/gendist",
    )

    JLLWrappers.@init_executable_product(
        kitsch,
        "bin/kitsch",
    )

    JLLWrappers.@init_executable_product(
        mix,
        "bin/mix",
    )

    JLLWrappers.@init_executable_product(
        move,
        "bin/move",
    )

    JLLWrappers.@init_executable_product(
        neighbor,
        "bin/neighbor",
    )

    JLLWrappers.@init_executable_product(
        pars,
        "bin/pars",
    )

    JLLWrappers.@init_executable_product(
        penny,
        "bin/penny",
    )

    JLLWrappers.@init_executable_product(
        proml,
        "bin/proml",
    )

    JLLWrappers.@init_executable_product(
        promlk,
        "bin/promlk",
    )

    JLLWrappers.@init_executable_product(
        protdist,
        "bin/protdist",
    )

    JLLWrappers.@init_executable_product(
        protpars,
        "bin/protpars",
    )

    JLLWrappers.@init_executable_product(
        restdist,
        "bin/restdist",
    )

    JLLWrappers.@init_executable_product(
        restml,
        "bin/restml",
    )

    JLLWrappers.@init_executable_product(
        retree,
        "bin/retree",
    )

    JLLWrappers.@init_executable_product(
        seqboot,
        "bin/seqboot",
    )

    JLLWrappers.@init_executable_product(
        treedist,
        "bin/treedist",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
