# Autogenerated wrapper script for PHYLIP_jll for i686-w64-mingw32
export clique, consense, contml, contrast, dnacomp, dnadist, dnainvar, dnaml, dnamlk, dnamove, dnapars, dnapenny, dollop, dolmove, dolpenny, drawgram, drawtree, factor, fitch, gendist, kitsch, libdrawgram, libdrawtree, mix, move, neighbor, pars, penny, proml, promlk, protdist, protpars, restdist, restml, retree, seqboot, treedist

JLLWrappers.@generate_wrapper_header("PHYLIP")
JLLWrappers.@declare_library_product(libdrawgram, "drawgram.dll")
JLLWrappers.@declare_library_product(libdrawtree, "drawtree.dll")
JLLWrappers.@declare_executable_product(clique)
JLLWrappers.@declare_executable_product(consense)
JLLWrappers.@declare_executable_product(contml)
JLLWrappers.@declare_executable_product(contrast)
JLLWrappers.@declare_executable_product(dnacomp)
JLLWrappers.@declare_executable_product(dnadist)
JLLWrappers.@declare_executable_product(dnainvar)
JLLWrappers.@declare_executable_product(dnaml)
JLLWrappers.@declare_executable_product(dnamlk)
JLLWrappers.@declare_executable_product(dnamove)
JLLWrappers.@declare_executable_product(dnapars)
JLLWrappers.@declare_executable_product(dnapenny)
JLLWrappers.@declare_executable_product(dollop)
JLLWrappers.@declare_executable_product(dolmove)
JLLWrappers.@declare_executable_product(dolpenny)
JLLWrappers.@declare_executable_product(drawgram)
JLLWrappers.@declare_executable_product(drawtree)
JLLWrappers.@declare_executable_product(factor)
JLLWrappers.@declare_executable_product(fitch)
JLLWrappers.@declare_executable_product(gendist)
JLLWrappers.@declare_executable_product(kitsch)
JLLWrappers.@declare_executable_product(mix)
JLLWrappers.@declare_executable_product(move)
JLLWrappers.@declare_executable_product(neighbor)
JLLWrappers.@declare_executable_product(pars)
JLLWrappers.@declare_executable_product(penny)
JLLWrappers.@declare_executable_product(proml)
JLLWrappers.@declare_executable_product(promlk)
JLLWrappers.@declare_executable_product(protdist)
JLLWrappers.@declare_executable_product(protpars)
JLLWrappers.@declare_executable_product(restdist)
JLLWrappers.@declare_executable_product(restml)
JLLWrappers.@declare_executable_product(retree)
JLLWrappers.@declare_executable_product(seqboot)
JLLWrappers.@declare_executable_product(treedist)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libdrawgram,
        "bin\\drawgram.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libdrawtree,
        "bin\\drawtree.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        clique,
        "bin\\clique.exe",
    )

    JLLWrappers.@init_executable_product(
        consense,
        "bin\\consense.exe",
    )

    JLLWrappers.@init_executable_product(
        contml,
        "bin\\contml.exe",
    )

    JLLWrappers.@init_executable_product(
        contrast,
        "bin\\contrast.exe",
    )

    JLLWrappers.@init_executable_product(
        dnacomp,
        "bin\\dnacomp.exe",
    )

    JLLWrappers.@init_executable_product(
        dnadist,
        "bin\\dnadist.exe",
    )

    JLLWrappers.@init_executable_product(
        dnainvar,
        "bin\\dnainvar.exe",
    )

    JLLWrappers.@init_executable_product(
        dnaml,
        "bin\\dnaml.exe",
    )

    JLLWrappers.@init_executable_product(
        dnamlk,
        "bin\\dnamlk.exe",
    )

    JLLWrappers.@init_executable_product(
        dnamove,
        "bin\\dnamove.exe",
    )

    JLLWrappers.@init_executable_product(
        dnapars,
        "bin\\dnapars.exe",
    )

    JLLWrappers.@init_executable_product(
        dnapenny,
        "bin\\dnapenny.exe",
    )

    JLLWrappers.@init_executable_product(
        dollop,
        "bin\\dollop.exe",
    )

    JLLWrappers.@init_executable_product(
        dolmove,
        "bin\\dolmove.exe",
    )

    JLLWrappers.@init_executable_product(
        dolpenny,
        "bin\\dolpenny.exe",
    )

    JLLWrappers.@init_executable_product(
        drawgram,
        "bin\\drawgram.exe",
    )

    JLLWrappers.@init_executable_product(
        drawtree,
        "bin\\drawtree.exe",
    )

    JLLWrappers.@init_executable_product(
        factor,
        "bin\\factor.exe",
    )

    JLLWrappers.@init_executable_product(
        fitch,
        "bin\\fitch.exe",
    )

    JLLWrappers.@init_executable_product(
        gendist,
        "bin\\gendist.exe",
    )

    JLLWrappers.@init_executable_product(
        kitsch,
        "bin\\kitsch.exe",
    )

    JLLWrappers.@init_executable_product(
        mix,
        "bin\\mix.exe",
    )

    JLLWrappers.@init_executable_product(
        move,
        "bin\\move.exe",
    )

    JLLWrappers.@init_executable_product(
        neighbor,
        "bin\\neighbor.exe",
    )

    JLLWrappers.@init_executable_product(
        pars,
        "bin\\pars.exe",
    )

    JLLWrappers.@init_executable_product(
        penny,
        "bin\\penny.exe",
    )

    JLLWrappers.@init_executable_product(
        proml,
        "bin\\proml.exe",
    )

    JLLWrappers.@init_executable_product(
        promlk,
        "bin\\promlk.exe",
    )

    JLLWrappers.@init_executable_product(
        protdist,
        "bin\\protdist.exe",
    )

    JLLWrappers.@init_executable_product(
        protpars,
        "bin\\protpars.exe",
    )

    JLLWrappers.@init_executable_product(
        restdist,
        "bin\\restdist.exe",
    )

    JLLWrappers.@init_executable_product(
        restml,
        "bin\\restml.exe",
    )

    JLLWrappers.@init_executable_product(
        retree,
        "bin\\retree.exe",
    )

    JLLWrappers.@init_executable_product(
        seqboot,
        "bin\\seqboot.exe",
    )

    JLLWrappers.@init_executable_product(
        treedist,
        "bin\\treedist.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
